services:
  app:
    build: .
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ../fitpro_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../fitpro_api:/app
    env_file:
      - ../fitpro_api/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
