import type { CSSProperties } from 'react';

export const styles = {
  root: {
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    maxWidth: 480,
    margin: '0 auto',
    padding: '8px 0',
  },
  card: {
    background: '#111111',
    border: '0.5px solid #333333',
    borderRadius: 12,
    padding: '24px 20px',
  },
  title: {
    fontSize: 15,
    fontWeight: 500,
    color: '#ffffff',
    margin: '0 0 16px',
    textAlign: 'center',
    letterSpacing: '-0.02em',
  },
  segControl: {
    display: 'flex',
    background: 'rgba(255,255,255,0.04)',
    border: '0.5px solid #333',
    borderRadius: 8,
    padding: 3,
    marginBottom: 8,
  },
  segBtn: {
    flex: 1,
    padding: '7px 4px',
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    color: '#666',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    transition: 'all 0.18s',
  },
  segBtnActive: {
    background: 'rgba(55, 138, 221, 0.15)',
    color: '#63a6e9',
  },
  viewport: {
    position: 'relative',
    height: 380,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    margin: '12px 0',
    borderRadius: 8,
    background: '#0a0a0a',
    border: '0.5px solid #222',
    cursor: 'default',
  },
  silhouette: {
    position: 'absolute',
    height: '88%',
    opacity: 0.12,
    filter: 'invert(1)',
    pointerEvents: 'none',
  },
  muscle: {
    position: 'absolute',
    height: '88%',
    aspectRatio: '594.276 / 841.89',
    transition: 'filter 0.35s ease, transform 0.15s ease',
  },
  legend: {
    display: 'flex',
    gap: 10,
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginTop: 10,
    marginBottom: 4,
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
  },
  legendDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
  },
  legendLabel: {
    fontSize: 11,
    color: '#666',
  },
  inspector: {
    background: '#0d0d0d',
    border: '0.5px solid #2a2a2a',
    borderRadius: 10,
    padding: 16,
    marginTop: 12,
  },
  inspectorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  muscleLabel: {
    fontSize: 11,
    fontWeight: 500,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#666',
    marginRight: 8,
  },
  badge: {
    display: 'inline-block',
    fontSize: 11,
    fontWeight: 500,
    padding: '2px 8px',
    borderRadius: 6,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#555',
    fontSize: 20,
    lineHeight: 1,
    padding: 0,
  },
  pctRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 6,
    marginBottom: 12,
  },
  pctValue: {
    fontSize: 30,
    fontWeight: 300,
    color: '#fff',
    letterSpacing: '-0.04em',
  },
  pctLabel: {
    fontSize: 12,
    color: '#555',
  },
  slider: {
    width: '100%',
    accentColor: '#fff',
  },
  actionBar: {
    display: 'flex',
    gap: 8,
    marginTop: 12,
  },
  btn: {
    flex: 1,
    padding: '8px 12px',
    borderRadius: 8,
    border: '0.5px solid #333',
    background: '#111',
    color: '#666',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    transition: 'all 0.18s',
  },
  btnActive: {
    background: 'rgba(55,138,221,0.12)',
    color: '#63a6e9',
    borderColor: 'rgba(55,138,221,0.25)',
  },
} satisfies Record<string, CSSProperties>;
