import type { CSSProperties } from 'react';

/**
 * Estilos del tracker anatómico. Integrados con los design tokens globales
 * (`--bg-*`, `--text-*`, `--brand`, etc.) definidos en `src/index.css` para
 * heredar automáticamente el tema claro/oscuro del resto de la app.
 */
export const styles = {
  root: {
    fontFamily: 'inherit',
    maxWidth: 480,
    margin: '0 auto',
    padding: '12px 14px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },

  /* ─── Header ──────────────────────────────────────── */
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '4px 2px 6px',
  },
  headerIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    background: 'linear-gradient(135deg, var(--brand), #15803d)',
    boxShadow: '0 8px 22px rgba(34,197,94,.28)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  headerText: { flex: 1, minWidth: 0 },
  headerTitle: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 18,
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: '-0.02em',
    color: 'var(--text-primary)',
    margin: 0,
  },
  headerSubtitle: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    margin: '2px 0 0',
  },

  /* ─── Card contenedora ───────────────────────────── */
  card: {
    padding: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },

  /* ─── Controles segmentados ──────────────────────── */
  controlsRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  segControl: {
    position: 'relative',
    display: 'flex',
    background: 'var(--bg-overlay)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 11,
    padding: 3,
  },
  segBtn: {
    position: 'relative',
    flex: 1,
    padding: '8px 6px',
    borderRadius: 8,
    border: 'none',
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 12.5,
    fontWeight: 600,
    fontFamily: 'inherit',
    letterSpacing: '0.01em',
    transition: 'color .18s ease',
    zIndex: 1,
  },
  segBtnActive: {
    color: 'var(--text-primary)',
  },
  segIndicator: {
    position: 'absolute',
    top: 3,
    bottom: 3,
    borderRadius: 8,
    background: 'var(--bg-card)',
    boxShadow: '0 1px 3px rgba(0,0,0,.35), 0 0 0 1px var(--border-subtle)',
    transition: 'left .22s cubic-bezier(.4,0,.2,1), width .22s cubic-bezier(.4,0,.2,1)',
    zIndex: 0,
  },

  /* ─── Viewport ──────────────────────────────────── */
  viewport: {
    position: 'relative',
    aspectRatio: '3 / 4',
    maxHeight: '58vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 14,
    background:
      'radial-gradient(ellipse at 50% 38%, rgba(34,197,94,.08) 0%, rgba(88,166,255,.04) 35%, transparent 70%), var(--bg-base)',
    border: '1px solid var(--border-subtle)',
    cursor: 'default',
    touchAction: 'manipulation',
  },
  silhouette: {
    position: 'absolute',
    height: '90%',
    opacity: 0.1,
    filter: 'invert(1)',
    pointerEvents: 'none',
  },
  muscle: {
    position: 'absolute',
    height: '90%',
    aspectRatio: '594.276 / 841.89',
    transition: 'filter 0.35s ease, transform 0.15s ease',
  },

  /* ─── Leyenda ───────────────────────────────────── */
  legend: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    justifyContent: 'center',
    padding: '2px 0',
  },
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 10px',
    borderRadius: 999,
    background: 'var(--bg-overlay)',
    border: '1px solid var(--border-subtle)',
  },
  legendDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
    boxShadow: '0 0 0 2px rgba(255,255,255,0.04)',
  },
  legendLabel: {
    fontSize: 10.5,
    fontWeight: 500,
    color: 'var(--text-secondary)',
    letterSpacing: '0.01em',
  },

  /* ─── Inspector ─────────────────────────────────── */
  inspector: {
    padding: 16,
    borderRadius: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
  },
  inspectorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  inspectorMeta: { display: 'flex', flexDirection: 'column', gap: 6, minWidth: 0, flex: 1 },
  muscleLabel: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: '-0.01em',
    color: 'var(--text-primary)',
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  muscleHint: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: 'var(--text-muted)',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 10.5,
    fontWeight: 700,
    padding: '4px 9px',
    borderRadius: 999,
    letterSpacing: '0.02em',
    alignSelf: 'flex-start',
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    background: 'var(--bg-overlay)',
    border: '1px solid var(--border-subtle)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    padding: 0,
    flexShrink: 0,
    transition: 'color .15s ease, background .15s ease, border-color .15s ease',
  },
  pctRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
  },
  pctValue: {
    fontFamily: "'Sora', sans-serif",
    fontSize: 38,
    fontWeight: 700,
    color: 'var(--text-primary)',
    letterSpacing: '-0.04em',
    lineHeight: 1,
  },
  pctLabel: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
    color: 'var(--text-muted)',
  },
  sliderWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  quickRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: 6,
  },
  quickChip: {
    padding: '6px 0',
    borderRadius: 8,
    border: '1px solid var(--border-subtle)',
    background: 'var(--bg-overlay)',
    color: 'var(--text-secondary)',
    fontSize: 11,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'inherit',
    letterSpacing: '0.01em',
    transition: 'all .15s ease',
  },
  quickChipActive: {
    background: 'var(--brand-dim)',
    color: 'var(--brand-bright)',
    borderColor: 'rgba(34,197,94,.35)',
  },

  /* ─── Action bar ────────────────────────────────── */
  actionBar: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 8,
  },
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: '11px 14px',
    borderRadius: 11,
    border: '1px solid var(--border)',
    background: 'var(--bg-overlay)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 12.5,
    fontWeight: 600,
    fontFamily: 'inherit',
    letterSpacing: '0.01em',
    transition: 'all .18s ease',
  },
  btnActive: {
    background: 'var(--brand-dim)',
    color: 'var(--brand-bright)',
    borderColor: 'rgba(34,197,94,.35)',
    boxShadow: '0 0 0 3px rgba(34,197,94,.08)',
  },
} satisfies Record<string, CSSProperties>;
